name: RPGCore
version: '1.0'
main: cz.vitekform.rPGCore.RPGCore
api-version: '1.21'
authors: [ ganamaga ]
website: https://ganamaga.me
commands:
  rpgcore:
    description: Main command for RPGCore
    usage: /rpgcore
    aliases:
      - rpg
      - rpgc
      - core
softdepend:
  - Oraxen