name: RPGCore
version: '1.0'
main: cz.vitekform.rPGCore.RPGCore
api-version: '1.21'
authors: [ vitekform ]
website: https://vitekform.cz
commands:
  rpgcore:
    description: Main command for RPGCore
    usage: /rpgcore
    aliases:
      - rpg
      - rpgc
      - core
  class:
    description: Main command for class management
    usage: /class
    aliases:
      - classes